### ISSUE TITLE
How to set it to edit the host?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [PascalNoisette/crontab-ui#14]
Hi

I'm not good with Docker, can you pls tell me how to make sure this container actually edits the crontab on the host?

TY

**Comment by YouveGotMeowxy** [comment]
When I try to run a command I just get this with your container?

> /tmp/2020421-8-an833i.56w17: line 1: sudo: not found

![image](https://user-images.githubusercontent.com/39491297/82614650-f917c500-9b8d-11ea-854f-0c682c42631a.png)

This is my compose:

```
version: "3"

services:

  crontab-ui:
    container_name: crontab-ui
    hostname: crontab-ui
    image: netpascal0123/crontab-ui:latest
    volumes:
      #- 'pi_crontabui:/crontab-ui/crontabs/'
      - 'pi_crontabui:/etc/crontabs/'
    ports:
      - '8000:8000'
    networks:
      - opm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

volumes:
  pi_crontabui:
    external: true

networks:
  opm:
    external:
      name: monitors
```

Appreciate any help! :)
